---
# registry play
- name: Setup docker registry
  hosts: registry-vm
  remote_user: vagrant
  become_method: ansible.builtin.sudo

  vars:
    vhome: /home/vagrant
    registry_addr: "192.168.33.8"
    registry_port: "5000"
    registry_username: "admin"
    registry_password: "password"

  tasks:
  - name: Update repositories cache
    ansible.builtin.apt:
      update_cache: true
    become: true

  - name: Safe system upgrade via aptitude
    ansible.builtin.apt:
      upgrade: safe
    become: true

  - name: Install apache2
    ansible.builtin.apt:
      name: apache2
      state: present
    become: true

  - name: Setup docker
    ansible.builtin.include_role:
      name: docker-registry

  - name: Configure registry
    ansible.builtin.include_role:
      name: configure-registry

# integration-server play
- name: Setup git CI server
  hosts: integration-server
  remote_user: vagrant
  become_method: ansible.builtin.sudo

  vars:
    vhome: /home/vagrant
    ci_server_address: 192.168.56.9/gitlab
    # TODO: pass these values into the ruby script
    server_root_password: "r00tr00t"
    server_user_name: "user"
    server_user_password: "us3rus3r"

    registry_addr: "192.168.33.8"
    registry_port: "5001"

  tasks:
  - name: Update repositories cache
    ansible.builtin.apt:
      update_cache: true
    become: true

  - name: Safe system upgrade via aptitude
    ansible.builtin.apt:
      upgrade: safe
    become: true

  - name: Download and install gitlab
    ansible.builtin.include_role:
      name: gitlab

  - name: Install docker
    ansible.builtin.include_role:
      name: docker-gitlab

# copying all the scripts into /tmp is better due to problems with permissions
  - name: Copy scripts to vagrant vm
    ansible.builtin.copy:
      src: ../ci-server/data/scripts
      dest: /tmp
      mode: u=rwx,g=rwx,o=rwx
    become: true

  - name: Create artefact repository
    ansible.builtin.file:
      path: "/shared/artefact-repository"
      mode: '0777'
      state: directory
    become: true

  - name: Configure gitlab
    ansible.builtin.include_role:
      name: configure-gitlab

  - name: Configure gitlab runner
    ansible.builtin.include_role:
      name: gitlab-runner

  - name: Configure registry on gitlab server
    ansible.builtin.include_role:
      name: configure-registry-gitlab

- name: Create project on gitlab
  hosts: integration-server
  become_method: ansible.builtin.sudo

  vars:
    ci_server_address: 192.168.56.9/gitlab
    # TODO: pass these values into the ruby script
    server_root_password: "r00tr00t"
    server_user_name: "user"
    server_user_password: "us3rus3r"

    registry_addr: "192.168.33.8"
    registry_port: "5000"
    repository_location: "../original_e4l"

  tasks:
  - name: Setup repo
    ansible.builtin.include_role:
      name: setup-repo
