# vim: ts=2
---
- name: Setup docker registry
  hosts: all
  remote_user: vagrant
  become_method: ansible.builtin.sudo

  vars:
    vhome: /home/vagrant
    registry_port: "5000"
    registry_addr: "192.168.33.8"
    registry_username: "admin"
    registry_password: "password"

  tasks:
    - name: Setup docker
      ansible.builtin.include_role:
        name: docker

    - name: Configure registry
      ansible.builtin.include_role:
        name: configure-registry
