- name: Change owner of the repo to vagrant
  ansible.builtin.file:
    path: "{{ vhome }}/therepo"
    owner: vagrant
    recurse: true

- name: Create project on CI server through gitlab API
  ansible.builtin.uri:
    url: "http://{{ ci_server_address }}/api/v4/projects?name=MavenHelloWorldProject"
    method: POST
    headers:
      PRIVATE-TOKEN: "{{ user_pat }}"
  ignore_errors: true

- name: Git init
  ansible.builtin.command:
    argv:
      - git
      - init
    chdir: "{{ vhome }}/therepo"
  ignore_errors: true

- name: Git remote add
  ansible.builtin.command:
    argv:
      - git
      - remote
      - add
      - origin
      - http://{{ ci_server_address }}/{{ server_user_name }}/MavenHelloWorldProject
    chdir: "{{ vhome }}/therepo"
  ignore_errors: true

- name: Git config set user.name
  ansible.builtin.command:
    argv:
      - git
      - config
      - --global
      - user.name
      - "user"
    chdir: "{{ vhome }}/therepo"
  ignore_errors: true

- name: Git config set user.email
  ansible.builtin.command:
    argv:
      - git
      - config
      - --global
      - user.email
      - "user@gmail.com"
    chdir: "{{ vhome }}/therepo"
  ignore_errors: true

- name: Git add .
  ansible.builtin.command:
    argv:
      - git
      - add
      - .
    chdir: "{{ vhome }}/therepo"
  ignore_errors: true

- name: Git commit
  ansible.builtin.command:
    argv:
      - git
      - commit
      - -m
      - 'Initial commit'
    chdir: "{{ vhome }}/therepo"
  ignore_errors: true

- name: Git push
  ansible.builtin.command:
    argv:
      - git
      - push
      - http://{{ server_user_name }}:{{ server_user_password }}@{{ ci_server_address }}/{{ server_user_name }}/MavenHelloWorldProject
      - master
    chdir: "{{ vhome }}/therepo"
  ignore_errors: true
