- name: Create project on CI server through gitlab API
  ansible.builtin.uri:
    url: "http://{{ ci_server_address }}/api/v4/projects?name={{ setup_repo_project_name }}"
    method: POST
    headers:
      PRIVATE-TOKEN: "{{ user_pat }}"
  ignore_errors: true
