- name: Change owner of the repo to vagrant
  ansible.builtin.file:
    path: "{{ vhome }}/therepo"
    owner: vagrant
    recurse: true

- name: Create project on CI server through gitlab API
  ansible.builtin.uri:
    url: http://192.168.56.9/gitlab/api/v4/projects?name=MavenHelloWorldProject
    method: POST
    headers:
      PRIVATE-TOKEN: "{{ user_pat }}"

- name: Git init
  ansible.builtin.command: git init
    chdir: "{{ vhome }}/therepo"

- name: Git remote add
  ansible.builtin.command: git remote add origin http://192.168.56.9/gitlab/user/MavenHelloWorldProject
    chdir: "{{ vhome }}/therepo"

- name: Git config set user.name
  ansible.builtin.command: git config --global user.name "user"
    chdir: "{{ vhome }}/therepo"

- name: Git config set user.email
  ansible.builtin.command: git config --global user.email "user@gmail.com"
    chdir: "{{ vhome }}/therepo"

- name: Copy .gitignore into repo
  ansible.builtin.copy:
    src: ./data/.gitignore
    dest: "{{ vhome }}/therepo"
    mode: u=rwx,g=rwx,o=rwx

- name: Git add .
  ansible.builtin.command: git add .
    chdir: "{{ vhome }}/therepo"

- name: git commit
  ansible.builtin.command: git commit -m 'Initial commit'
    chdir: "{{ vhome }}/therepo"

- name: git push
  ansible.builtin.command: git push http://user:r00tr00t@192.168.56.9/gitlab/user/MavenHelloWorldProject master
    chdir: "{{ vhome }}/therepo"
