version: "3.5"

services:
  e4l-frontend-prod:
    restart: always
    image: ${CI_REGISTRY_IMAGE}:release
    container_name: e4l-frontend-prod
    ports:
      - 8885:80
    volumes:
      - /opt/e4l-news:/usr/share/nginx/news
    environment:
      - PUBLIC_PATH=
      - API_URL=/e4lapi
      - TZ=Europe/Luxembourg
