---

- name: Update repositories cache.
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install packages required by Docker.
  ansible.builtin.apt:
    name: "{{ packages }}"
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
  become: true

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
  become: true

- name: Update repositories cache.
  ansible.builtin.apt:
    update_cache: true
  become: true


- name: Install Docker packages.
  ansible.builtin.apt:
    name: "{{ dockerpackages }}"
  vars:
    dockerpackages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  become: true


- name: Add users to docker group.
  ansible.builtin.user:
    name: vagrant
    append: true
    groups: docker
  become: true

- name: Verify docker installation
  ansible.builtin.command: docker --version
  changed_when: false
  become: true
